[colors.primary]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_background.default.hex}}"

[colors.cursor]
text   = "{{colors.background.default.hex}}"
cursor = "{{colors.on_surface.default.hex}}"

[colors.selection]
text       = "{{colors.on_secondary_container.default.hex}}"
background = "{{colors.secondary_container.default.hex}}"

[colors.normal]
black   = "{{colors.surface_dim.default.hex}}"
red     = "{{colors.error.default.hex}}"
green   = "{{colors.tertiary.default.hex}}"
yellow  = "{{colors.secondary.default.hex}}"
blue    = "{{colors.primary.default.hex}}"
magenta = "{{colors.secondary_container.default.hex}}"
cyan    = "{{colors.tertiary_container.default.hex}}"
white   = "{{colors.on_surface.default.hex}}"

[colors.bright]
black   = "{{colors.surface_variant.default.hex}}"
red     = "{{colors.error.default.hex | lighten: 12.0}}"
green   = "{{colors.tertiary.default.hex | lighten: 12.0}}"
yellow  = "{{colors.secondary.default.hex | lighten: 12.0}}"
blue    = "{{colors.primary.default.hex | lighten: 12.0}}"
magenta = "{{colors.secondary_container.default.hex | lighten: 8.0}}"
cyan    = "{{colors.tertiary_container.default.hex | lighten: 8.0}}"
white   = "{{colors.on_surface_variant.default.hex}}"
